CREATE TABLE `config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `value` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

INSERT INTO `config` (`id`, `key`, `name`, `description`, `value`) VALUES
(1, 'site_title', 'Title', 'Site title as displayed in the title bar', 'Backoff frontend sample'),
(2, 'site_description', 'Description', 'Site description, as displayed in search engines', 'This is a sample website made for backoff'),
(3, 'site_keywords', 'Keywords', 'comma separated keywords list', 'backoff, backoffice, php, admin generator'),
(8, 'google_ga', 'Google Analitycs ID', 'Google Analitycs ID', 'UA-XXXXXXX-X');

CREATE TABLE `contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subject` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `from` varchar(255) NOT NULL,
  `to` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `date` datetime NOT NULL,
  `admin` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_code` varchar(2) NOT NULL DEFAULT '',
  `country_name` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `countries` (`id`, `country_code`, `country_name`) VALUES
(1, 'US', 'United States'),
(2, 'CA', 'Canada'),
(3, 'AF', 'Afghanistan'),
(4, 'AL', 'Albania'),
(5, 'DZ', 'Algeria'),
(6, 'DS', 'American Samoa'),
(7, 'AD', 'Andorra'),
(8, 'AO', 'Angola'),
(9, 'AI', 'Anguilla'),
(10, 'AQ', 'Antarctica'),
(11, 'AG', 'Antigua and/or Barbuda'),
(12, 'AR', 'Argentina'),
(13, 'AM', 'Armenia'),
(14, 'AW', 'Aruba'),
(15, 'AU', 'Australia'),
(16, 'AT', 'Austria'),
(17, 'AZ', 'Azerbaijan'),
(18, 'BS', 'Bahamas'),
(19, 'BH', 'Bahrain'),
(20, 'BD', 'Bangladesh'),
(21, 'BB', 'Barbados'),
(22, 'BY', 'Belarus'),
(23, 'BE', 'Belgium'),
(24, 'BZ', 'Belize'),
(25, 'BJ', 'Benin'),
(26, 'BM', 'Bermuda'),
(27, 'BT', 'Bhutan'),
(28, 'BO', 'Bolivia'),
(29, 'BA', 'Bosnia and Herzegovina'),
(30, 'BW', 'Botswana'),
(31, 'BV', 'Bouvet Island'),
(32, 'BR', 'Brazil'),
(33, 'IO', 'British lndian Ocean Territory'),
(34, 'BN', 'Brunei Darussalam'),
(35, 'BG', 'Bulgaria'),
(36, 'BF', 'Burkina Faso'),
(37, 'BI', 'Burundi'),
(38, 'KH', 'Cambodia'),
(39, 'CM', 'Cameroon'),
(40, 'CV', 'Cape Verde'),
(41, 'KY', 'Cayman Islands'),
(42, 'CF', 'Central African Republic'),
(43, 'TD', 'Chad'),
(44, 'CL', 'Chile'),
(45, 'CN', 'China'),
(46, 'CX', 'Christmas Island'),
(47, 'CC', 'Cocos (Keeling) Islands'),
(48, 'CO', 'Colombia'),
(49, 'KM', 'Comoros'),
(50, 'CG', 'Congo'),
(51, 'CK', 'Cook Islands'),
(52, 'CR', 'Costa Rica'),
(53, 'HR', 'Croatia (Hrvatska)'),
(54, 'CU', 'Cuba'),
(55, 'CY', 'Cyprus'),
(56, 'CZ', 'Czech Republic'),
(57, 'DK', 'Denmark'),
(58, 'DJ', 'Djibouti'),
(59, 'DM', 'Dominica'),
(60, 'DO', 'Dominican Republic'),
(61, 'TP', 'East Timor'),
(62, 'EC', 'Ecudaor'),
(63, 'EG', 'Egypt'),
(64, 'SV', 'El Salvador'),
(65, 'GQ', 'Equatorial Guinea'),
(66, 'ER', 'Eritrea'),
(67, 'EE', 'Estonia'),
(68, 'ET', 'Ethiopia'),
(69, 'FK', 'Falkland Islands (Malvinas)'),
(70, 'FO', 'Faroe Islands'),
(71, 'FJ', 'Fiji'),
(72, 'FI', 'Finland'),
(73, 'FR', 'France'),
(74, 'FX', 'France, Metropolitan'),
(75, 'GF', 'French Guiana'),
(76, 'PF', 'French Polynesia'),
(77, 'TF', 'French Southern Territories'),
(78, 'GA', 'Gabon'),
(79, 'GM', 'Gambia'),
(80, 'GE', 'Georgia'),
(81, 'DE', 'Germany'),
(82, 'GH', 'Ghana'),
(83, 'GI', 'Gibraltar'),
(84, 'GR', 'Greece'),
(85, 'GL', 'Greenland'),
(86, 'GD', 'Grenada'),
(87, 'GP', 'Guadeloupe'),
(88, 'GU', 'Guam'),
(89, 'GT', 'Guatemala'),
(90, 'GN', 'Guinea'),
(91, 'GW', 'Guinea-Bissau'),
(92, 'GY', 'Guyana'),
(93, 'HT', 'Haiti'),
(94, 'HM', 'Heard and Mc Donald Islands'),
(95, 'HN', 'Honduras'),
(96, 'HK', 'Hong Kong'),
(97, 'HU', 'Hungary'),
(98, 'IS', 'Iceland'),
(99, 'IN', 'India'),
(100, 'ID', 'Indonesia'),
(101, 'IR', 'Iran (Islamic Republic of)'),
(102, 'IQ', 'Iraq'),
(103, 'IE', 'Ireland'),
(104, 'IL', 'Israel'),
(105, 'IT', 'Italy'),
(106, 'CI', 'Ivory Coast'),
(107, 'JM', 'Jamaica'),
(108, 'JP', 'Japan'),
(109, 'JO', 'Jordan'),
(110, 'KZ', 'Kazakhstan'),
(111, 'KE', 'Kenya'),
(112, 'KI', 'Kiribati'),
(113, 'KP', 'Korea, Democratic People''s Republic of'),
(114, 'KR', 'Korea, Republic of'),
(115, 'KW', 'Kuwait'),
(116, 'KG', 'Kyrgyzstan'),
(117, 'LA', 'Lao People''s Democratic Republic'),
(118, 'LV', 'Latvia'),
(119, 'LB', 'Lebanon'),
(120, 'LS', 'Lesotho'),
(121, 'LR', 'Liberia'),
(122, 'LY', 'Libyan Arab Jamahiriya'),
(123, 'LI', 'Liechtenstein'),
(124, 'LT', 'Lithuania'),
(125, 'LU', 'Luxembourg'),
(126, 'MO', 'Macau'),
(127, 'MK', 'Macedonia'),
(128, 'MG', 'Madagascar'),
(129, 'MW', 'Malawi'),
(130, 'MY', 'Malaysia'),
(131, 'MV', 'Maldives'),
(132, 'ML', 'Mali'),
(133, 'MT', 'Malta'),
(134, 'MH', 'Marshall Islands'),
(135, 'MQ', 'Martinique'),
(136, 'MR', 'Mauritania'),
(137, 'MU', 'Mauritius'),
(138, 'TY', 'Mayotte'),
(139, 'MX', 'Mexico'),
(140, 'FM', 'Micronesia, Federated States of'),
(141, 'MD', 'Moldova, Republic of'),
(142, 'MC', 'Monaco'),
(143, 'MN', 'Mongolia'),
(144, 'MS', 'Montserrat'),
(145, 'MA', 'Morocco'),
(146, 'MZ', 'Mozambique'),
(147, 'MM', 'Myanmar'),
(148, 'NA', 'Namibia'),
(149, 'NR', 'Nauru'),
(150, 'NP', 'Nepal'),
(151, 'NL', 'Netherlands'),
(152, 'AN', 'Netherlands Antilles'),
(153, 'NC', 'New Caledonia'),
(154, 'NZ', 'New Zealand'),
(155, 'NI', 'Nicaragua'),
(156, 'NE', 'Niger'),
(157, 'NG', 'Nigeria'),
(158, 'NU', 'Niue'),
(159, 'NF', 'Norfork Island'),
(160, 'MP', 'Northern Mariana Islands'),
(161, 'NO', 'Norway'),
(162, 'OM', 'Oman'),
(163, 'PK', 'Pakistan'),
(164, 'PW', 'Palau'),
(165, 'PA', 'Panama'),
(166, 'PG', 'Papua New Guinea'),
(167, 'PY', 'Paraguay'),
(168, 'PE', 'Peru'),
(169, 'PH', 'Philippines'),
(170, 'PN', 'Pitcairn'),
(171, 'PL', 'Poland'),
(172, 'PT', 'Portugal'),
(173, 'PR', 'Puerto Rico'),
(174, 'QA', 'Qatar'),
(175, 'RE', 'Reunion'),
(176, 'RO', 'Romania'),
(177, 'RU', 'Russian Federation'),
(178, 'RW', 'Rwanda'),
(179, 'KN', 'Saint Kitts and Nevis'),
(180, 'LC', 'Saint Lucia'),
(181, 'VC', 'Saint Vincent and the Grenadines'),
(182, 'WS', 'Samoa'),
(183, 'SM', 'San Marino'),
(184, 'ST', 'Sao Tome and Principe'),
(185, 'SA', 'Saudi Arabia'),
(186, 'SN', 'Senegal'),
(187, 'SC', 'Seychelles'),
(188, 'SL', 'Sierra Leone'),
(189, 'SG', 'Singapore'),
(190, 'SK', 'Slovakia'),
(191, 'SI', 'Slovenia'),
(192, 'SB', 'Solomon Islands'),
(193, 'SO', 'Somalia'),
(194, 'ZA', 'South Africa'),
(195, 'GS', 'South Georgia South Sandwich Islands'),
(196, 'ES', 'Spain'),
(197, 'LK', 'Sri Lanka'),
(198, 'SH', 'St. Helena'),
(199, 'PM', 'St. Pierre and Miquelon'),
(200, 'SD', 'Sudan'),
(201, 'SR', 'Suriname'),
(202, 'SJ', 'Svalbarn and Jan Mayen Islands'),
(203, 'SZ', 'Swaziland'),
(204, 'SE', 'Sweden'),
(205, 'CH', 'Switzerland'),
(206, 'SY', 'Syrian Arab Republic'),
(207, 'TW', 'Taiwan'),
(208, 'TJ', 'Tajikistan'),
(209, 'TZ', 'Tanzania, United Republic of'),
(210, 'TH', 'Thailand'),
(211, 'TG', 'Togo'),
(212, 'TK', 'Tokelau'),
(213, 'TO', 'Tonga'),
(214, 'TT', 'Trinidad and Tobago'),
(215, 'TN', 'Tunisia'),
(216, 'TR', 'Turkey'),
(217, 'TM', 'Turkmenistan'),
(218, 'TC', 'Turks and Caicos Islands'),
(219, 'TV', 'Tuvalu'),
(220, 'UG', 'Uganda'),
(221, 'UA', 'Ukraine'),
(222, 'AE', 'United Arab Emirates'),
(223, 'GB', 'United Kingdom'),
(224, 'UM', 'United States minor outlying islands'),
(225, 'UY', 'Uruguay'),
(226, 'UZ', 'Uzbekistan'),
(227, 'VU', 'Vanuatu'),
(228, 'VA', 'Vatican City State'),
(229, 'VE', 'Venezuela'),
(230, 'VN', 'Vietnam'),
(231, 'VG', 'Virigan Islands (British)'),
(232, 'VI', 'Virgin Islands (U.S.)'),
(233, 'WF', 'Wallis and Futuna Islands'),
(234, 'EH', 'Western Sahara'),
(235, 'YE', 'Yemen'),
(236, 'YU', 'Yugoslavia'),
(237, 'ZR', 'Zaire'),
(238, 'ZM', 'Zambia'),
(239, 'ZW', 'Zimbabwe');

CREATE TABLE `galery` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image` varchar(255) NOT NULL,
  `thumbnail` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `id_page` int(11) NOT NULL,
  `position` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

INSERT INTO `galery` (`id`, `image`, `thumbnail`, `title`, `id_page`, `position`, `status`) VALUES
(3, 'Sky.jpg', 'Sky.jpg', 'Sky', 3, 0, 1);

CREATE TABLE `newsletter_campains` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_letter` int(11) NOT NULL,
  `date` datetime NOT NULL,
  `date_end` datetime NOT NULL,
  `sent` int(11) NOT NULL,
  `active` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `newsletter_emails` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `date` datetime NOT NULL,
  `active` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE `newsletter_letters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from_name` varchar(255) NOT NULL,
  `from_email` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `body_html` text NOT NULL,
  `body_text` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `id_module` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `status` tinyint(1) NOT NULL,
  `position` int(11) NOT NULL,
  `status_en` tinyint(1) NOT NULL,
  `title_en` varchar(250) NOT NULL,
  `content_en` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

INSERT INTO `pages` (`id`, `url`, `name`, `id_module`, `content`, `status`, `position`, `status_en`, `title_en`, `content_en`) VALUES
(1, '', 'Home', '1', '<div class="jumbotron">\r\n<h1>Jumbotron heading</h1>\r\n<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>\r\n<p><a class="btn btn-lg btn-success" href="#">Sign up today</a></p>\r\n</div>\r\n<div class="row marketing">\r\n<div class="col-lg-6">\r\n<h4>Subheading</h4>\r\n<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>\r\n<h4>Subheading</h4>\r\n<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>\r\n<h4>Subheading</h4>\r\n<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>\r\n</div>\r\n<div class="col-lg-6">\r\n<h4>Subheading</h4>\r\n<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>\r\n<h4>Subheading</h4>\r\n<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>\r\n<h4>Subheading</h4>\r\n<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>\r\n</div>\r\n</div>', 1, 0, 0, 'Home', '<h1><span style="color: rgb(128, 128, 128);">Welcome to&nbsp;&ldquo;le</span> Caf&eacute; du Commerce&rdquo; !</h1>\r\n<a href="photos/"><img width="160" height="234" align="left" class="thumb" alt="" style="margin-right: 10px;" src="/documents/images/visuels/visuel_accueil.jpg" /></a>\r\n<p><b>Un bistro parisien authentique ...</b></p>\r\n<p style="text-align: justify;">Situ&eacute; dans une des rues les plus anim&eacute;es et typiques du XV&egrave; arrondissement, tout pr&egrave;s de la Tour Eiffel, Le Caf&eacute; du Commerce c''est la cuisine de tradition par excellence, une s&eacute;lection de recettes authentiques &agrave; red&eacute;couvrir : du poireau vinaigrette &agrave; l''oeuf mayonnaise en passant par l''exceptionnelle viande limousine...</p>\r\n<p style="text-align: right;"><b>... Au cadre spacieux et chaleureux</b></p>\r\n<p style="text-align: justify;">Unique &agrave; Paris, le Caf&eacute; du Commerce vous accueille le long de ses 3 &eacute;tages orn&eacute;s de plantes et ouverts sur le ciel de Paris. A deux ou en groupe, partagez l''intimit&eacute; ou la convivialit&eacute; d''une bonne table o&ugrave; le service porte haut les couleurs de Paris.</p>\r\n<a href="./?page=restaurant">â–¸ En savoir plus<br />\r\n<br />\r\n</a>\r\n<table width="100%" cellspacing="0" cellpadding="0">\r\n    <tbody>\r\n        <tr>\r\n            <td width="35%" valign="top">\r\n            <h2>Infos pratiques</h2>\r\n            <p><b>Le Caf&eacute; du Commerce</b><br />\r\n            51 rue du commerce <br />\r\n            75015 PARIS <br />\r\n            <strong>T&eacute;l :</strong> +33.1.45.75.03.27</p>\r\n            <p><b>R&eacute;servation de 8h00 &agrave; minuit</b><br />\r\n            Ouvert tous les jours <br />\r\n            de 12h &agrave; 15h et de 19h &agrave; minuit.</p>\r\n            <p><img width="15" height="15" alt="" src="/documents/images/visuels/metro.gif" /> La Motte Piquet, Emile Zola, <br />\r\n            &nbsp;&nbsp;&nbsp;&nbsp; Commerce.<br />\r\n            <img width="15" height="15" alt="" src="/documents/images/visuels/parking.gif" /> &agrave; 30m : 104, rue du th&eacute;atre <br />\r\n            <img alt="wifi" src="/documents/images/visuels/wifi.png" /> Connexion WiFi</p>\r\n            <p><a onClick="window.open(''http://resa.lafourchette.com/go.php?i=36&o=RE&h=bff9f''\r\n ,''_blank'',''width=412,height=566,resize=yes'');return false;" href="http://resa.lafourchette.com/go.php?i=36&amp;o=RE&amp;h=bff9f">â–¸ R&eacute;servez en ligne !</a><br />\r\n            <a href="plan/">â–¸ Plan d''acc&egrave;s</a></p>\r\n            <p>&nbsp;</p>\r\n            </td>\r\n            <td width="20">&nbsp;</td>\r\n            <td valign="top">\r\n            <h2>Actus</h2>\r\n            <strong><img width="100" height="71" align="right" class="thumb" alt="" style="margin-left: 10px;" src="/documents/images/visuels/logo_baisse_tva_h147.jpg" />Baisse de la TVA</strong><br />\r\n            <em>1er novembre 2008</em> : Face &agrave; la crise, le Caf&eacute; du commerce baisse ses prix de 12%.<br />\r\n            <em>1er Juillet 2009</em> : Le personnel r&eacute;mun&eacute;r&eacute; au pourcentage profiterad''une augmentation de salaire.&nbsp;Le Caf&eacute; du commerce s''engage &eacute;galement &agrave; augmenter les bas salaires (SMIC) de 10%.<br />\r\n            <a href="carte/">â–¸ D&eacute;couvrez nos nouveaux prix !</a><br />\r\n            <br />\r\n            <strong><img width="100" height="121" align="right" class="thumb" alt="" style="margin-left: 10px;" src="/documents/images/visuels/prix_jury_small.jpg" />Concours d''affiche</strong><br />\r\n            Etienne Guerraud et toute l&rsquo;&eacute;quipe du Caf&eacute; du Commerce vous invitent &agrave; d&eacute;couvrir les projets d&rsquo;affiches r&eacute;alis&eacute;s par de talentueux &eacute;tudiants d&rsquo;Arts Graphiques de deux &eacute;coles parisiennes, l''ECV et l''ENSAD. <br />\r\n            <a href="expo2008/">â–¸ Admirez le travail !</a></td>\r\n        </tr>\r\n    </tbody>\r\n</table>'),
(5, 'test', 'Test', '1', '<h1>h1. Heading <small>Secondary text</small></h1>\r\n<h2>h2. Heading <small>Secondary text</small></h2>\r\n<h3>h3. Heading <small>Secondary text</small></h3>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n<h4>List</h4>\r\n<ul>\r\n    <li><a href="http://google.com">Google</a></li>\r\n    <li><a href="http://yahoo.com">Yahoo</a></li>\r\n    <li>etc...</li>\r\n</ul>\r\n<h4>Styles</h4>\r\n<div><strong>Gras, </strong><em>Italique</em><em>,</em> <strike>barr&eacute;</strike>, <sup>indice,</sup> <small>petit</small>, normal, <big>grand </big></div>\r\n<h4>Table</h4>\r\n<table width="100%" cellspacing="1" cellpadding="1" border="1" style="border-collapse: collapse;" summary="R&eacute;sum&eacute;">\r\n    <caption>Titre du tableau</caption>\r\n    <tbody>\r\n        <tr>\r\n            <td>une</td>\r\n            <td>grande</td>\r\n            <td>table</td>\r\n        </tr>\r\n        <tr>\r\n            <td>&nbsp;</td>\r\n            <td>&nbsp;</td>\r\n            <td>&nbsp;</td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n<h4>Icons</h4>\r\n<ul class="bs-glyphicons">\r\n    <li><span class="glyphicon-class">.glyphicon .glyphicon-adjust</span></li>\r\n    <li><span class="glyphicon-class">.glyphicon .glyphicon-align-center</span></li>\r\n    <li><span class="glyphicon-class">.glyphicon .glyphicon-align-justify</span></li>\r\n    <li><span class="glyphicon-class">.glyphicon .glyphicon-align-left</span></li>\r\n</ul>', 1, 150, 0, '', ''),
(2, 'contact', 'Contact', '2', '<address><strong>Twitter, Inc.</strong><br />\r\n795 Folsom Ave, Suite 600<br />\r\nSan Francisco, CA 94107<br />\r\n<abbr title="Phone">P:</abbr> (123) 456-7890</address>\r\n<address><strong>Full Name</strong><br />\r\n<a href="mailto:#">first.last@example.com<br type="_moz" />\r\n</a></address>\r\n<iframe width="100%" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.fr/maps/ms?ie=UTF8&amp;msa=0&amp;msid=101686375028251599401.0004484f73bea6145ef6b&amp;ll=43.591667,3.867996&amp;spn=0,0&amp;output=embed&amp;s=AARTsJqhzeyiqiLGEqDCDC7ar_q7Q1nmAw"></iframe>', 1, 60, 0, '', '<br />'),
(3, 'album', 'Pictures', '3', '<h1>Some pictures</h1>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>', 1, 100, 0, 'Pictures', '<br />'),
(4, 'newsletter', 'Newsletter', '4', '<h1>Newsletter</h1>\r\n<span style="color: rgb(68, 68, 68);">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</span>', 1, 125, 0, '', '');

CREATE TABLE `pages_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

INSERT INTO `pages_modules` (`id`, `module`, `name`) VALUES
(1, 'content', 'Content page'),
(2, 'contact', 'Contact form'),
(3, 'galery', 'Image Galery'),
(4, 'newsletter', 'Newsletter');

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `date` datetime NOT NULL,
  `admin` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

INSERT INTO `users` (`id`, `username`, `password`, `email`, `date`, `admin`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'admin@domain.com', '0000-00-00 00:00:00', 1);
